### ISSUE TITLE
Blacklist does nothing

### ISSUE THREAD

**Issue by deeppomf** [CryShana/Sankaku-Channel-Downloader#12]
The program downloads images with blacklisted tags even though the programs says it skipped them. 

The culprit is in line 162 of MainViewModel.cs since the continue exits out of the foreach loop iterating over the blacklisted tags. Instead, it should exit out of the foreach loop iterating over the images.

**Comment by CryShana** [comment]
Sorry for the late response. I have noticed you have already fixed it. Thanks for the contribution.
