### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by trashtree** [CryShana/Sankaku-Channel-Downloader#15]
I downloaded all folders and files, but I can't figure out how to run the application. Is there an executable somewhere in the folders that I am missing?
Please tell me how to run this downloader. Thank you in advance.

**Comment by CryShana** [comment]
I'm guessing you downloaded the source code. If you just wish to use the program, you need to go under the "Release" tab and download the appropriate .zip there.

https://github.com/CryShana/Sankaku-Channel-Downloader/releases
