### ISSUE TITLE
can't download all of them

### ISSUE THREAD

**Issue by maxman2103** [CryShana/Sankaku-Channel-Downloader#17]
i was downloading a tag that contain 119 image but after 80 image it says task stopped.. used the latest version 
after that i went and used an old version(1.0.6) and with that i was able to download 113.

**Comment by CryShana** [comment]
When reporting such bugs you should tell me how to reproduce it so I can test it out. What tag did you use to get this? Also did this happen every time with this tag?

**Comment by maxman2103** [comment]
on version 1.0.6 i used ( hundred official_art ) tag. the webpage says there are 81 but it downloads 76

and for the new one ( shinmai_maou_no_testament official_art ) the page says there are 315 but it downloaded 260+ (can't remember the number, i deleted the download file later). the post/page was set to 50.

**Comment by CryShana** [comment]
I just tried **both tags** and I always got the **correct** number of posts downloaded. 81 for the first one and 315 for the second one. 

Did you get any errors while downloading? And did you try searching the same tag again?
I can't seem to reproduce the issue. 

I was also using the latest release (1.1.6) with default settings (skip nothing, 50 posts/page) and tried both concurrent and without concurrent downloading.

**Comment by maxman2103** [comment]
![jjj](https://user-images.githubusercontent.com/29353332/42460702-5d99f684-83c0-11e8-8964-1267a45aea9f.PNG)

**Comment by maxman2103** [comment]
![hljl](https://user-images.githubusercontent.com/29353332/42460767-8d758e4a-83c0-11e8-8edf-8b2b50b428b9.PNG)

**Comment by maxman2103** [comment]
i had screenshots of these 2...version 1.0.6 tag shirase_sakuya website says 585 downloaded 553 and tag seraphim_(kore_wa_zombie_desu_ka?) website says 331 downloader says 314

**Comment by CryShana** [comment]
oh, you are using the old 1.0.6 version. Try the latest one - 1.1.6
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1.6

**Comment by maxman2103** [comment]
![bfnfnf](https://user-images.githubusercontent.com/29353332/42470049-31704db8-83db-11e8-9b39-7da1f99e3bb3.PNG)


this is a bug right?

**Comment by CryShana** [comment]
yes. This was already mentioned here #14 - I haven't been able to reproduce it yet. Does this happen every time you search for this tag?

**Comment by maxman2103** [comment]
No sometime it happens with other tag as well...when i first used this tag it finished middle of the task t

**Comment by maxman2103** [comment]
OO i forgot to mention one more thing sometime it happens with a single tag and sometime it happens with more that one tag...but most of my download ended with task finished even thought they are not finished.

**Comment by CryShana** [comment]
The bug where the task stops in the middle of downloading has now been fixed in 1.1.7
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1.7

**Comment by maxman2103** [comment]
Thank You
