### ISSUE TITLE
Getting stuck in same place everytime

### ISSUE THREAD

**Issue by zearmhot** [CryShana/Sankaku-Channel-Downloader#21]
With the tags "-REMOVED-" this program always get stuck at page 11 at 52%, retries, and fails again. Sorry, I wish I could get you more family friendly tags to test with, but I can't reproduce this with anything else. If I start on Page 12, it works again. Seems to be an image on page 11 or something that is breaking the program.

I must say, outside of this, this program is incredible. I tried many booru downloaders and none of them could do Sankaku without major issues.

EDIT: Checking "Skip video files" prevents it. Must be some type of video file causing it.

EDIT2: Would be nice to have a "max retry" setting for these situations. If it fails 2-3 times, it should just ignore the file and move on.

**Comment by zearmhot** [comment]
Is there to see what file it get stuck on downloading? 

I just see a bunch of these:
[26.12.2018 08:02:46] HttpError - Trying again in 4 second/s -> Lost connection [0].

**Comment by zearmhot** [comment]
OK I figured out which videos are causing it:
md5:07e0b96770cb5859819f6875944c06c8
md5:a5ca47eb9f100920652a6044b0a55236

Weird videos, NSFW lol. These are over 100MB each and might be why it is failing.

**Comment by CryShana** [comment]
Alright. Go try out the latest release.
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1.9

**Comment by zearmhot** [comment]
Looks like it's fixed! Successfully grabbed a 170MB file without issue on the 4GB machine. Will reopen if it pops back up again. Thanks again,
