### ISSUE TITLE
Queuing multiple searches (Suggestion)

### ISSUE THREAD

**Issue by zearmhot** [CryShana/Sankaku-Channel-Downloader#22]
It would be nice if we could add a search and press a "+" icon to add it to a queue, then add additional searches before pressing start.

Not a huge deal, just a quality of life thing. Not sure how hard it'd be to add.

**Comment by zearmhot** [comment]
If you are looking for even more features to add in the future, I'd suggest adding options to include copywrite and character tags in the filename. So it'd look something like "copyright tags - character tags - MD5.jpg". 

Makes it a lot easier to figure out where an image is from.

**Comment by esotericer1** [comment]
Yeah, I would love to see file naming feature. Also, it would be wonderful to add 'ignore already downloaded files' feature. So if you move/remove the downloaded files and download from the same search tag it only downloads new images(by reading from a log file or something). If only these two features(1. file renaming feature 2. downloading only new images from the same tag) are integrated into the next upgrade then it would be wonderful! This program is the best way to download from the sankaku channel I've seen :) Keep up the good work!

**Comment by CryShana** [comment]
All right. Will try to do it by the end of this month when I get some time. Thanks for the feedback!

**Comment by esotericer1** [comment]
Thank you! Looking forward to it :)

2019년 3월 18일 (월) 오후 6:34, CryShana <notifications@github.com>님이 작성:

**Comment by CryShana** [comment]
In the latest 1.2 release I have now added a Job queue system and the ability to customize the file naming format. 

Download it here:
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.2

Skipping images based on a previous log of downloaded images will be implemented later...

**Comment by CryShana** [comment]
The original issue has now been resolved, so I will be closing it.
