### ISSUE TITLE
[Request] Option to include FileID to naming format

### ISSUE THREAD

**Issue by cmfc31** [CryShana/Sankaku-Channel-Downloader#23]
Could you add an option to customize the filename of the downloaded files?
As example: original_character-gosima_rinko-original-jabara_tornado-high_resolution-simple_background-white_background-fanbox_reward-1girl-areolae-sankaku-7915169.png

Combination of 10 first tags + sankaku + file id + file extension

**Comment by cmfc31** [comment]
Wait, you already added that haha. Nevermind then. You should update your screenshot at readme.

**Comment by cmfc31** [comment]
Could you add the option to add the file id to the naming formats? like [fileid]?
You get that from the post url, as ex:
https://chan.sankakucomplex.com/post/show/6700097 

6700097 is the file id, it's really useful when you want to see the original post in sankaku's site.

**Comment by CryShana** [comment]
Sure, will look into it.

**Comment by cmfc31** [comment]
Thanks! great app. I'm amazed how fast does the queries. Even when I use the main site to search my favorites, it takes a while to load all the posts but your program got them really quickly.

**Comment by CryShana** [comment]
Just added the File ID as an option and also updated the screenshot.

Check the latest release:
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.2.4
