### ISSUE TITLE
Problem when the tag have a "-" inside

### ISSUE THREAD

**Issue by kikims93s** [CryShana/Sankaku-Channel-Downloader#24]
Hi my friends, thanks for your work.

We have a issue when we use a tag with a composed term with a "-" inside like : "Ero-anime" 

Thanks ;)

**Comment by CryShana** [comment]
First of all - The "**Ero-anime**" tag doesn't even have any posts tagged with it (just checked on their website). 

I also tried another tag with "-" inside but didn't notice any issues. 

Can you give me exact steps on how to reproduce this issue? Or what kind of error are you getting?

**Comment by kikims93s** [comment]
Sur about this ? check : https://www.sankakucomplex.com/tag/ero-anime/

It's a tag

**Comment by CryShana** [comment]
You are confusing tags on the main site https://www.sankakucomplex.com/ with tags on **Sankaku Channel** https://chan.sankakucomplex.com/.
