### ISSUE TITLE
Error wile downloading some picture

### ISSUE THREAD

**Issue by Hellbeast** [CryShana/Sankaku-Channel-Downloader#27]
There is some problem on sankaku side or in app, on some tags happens continuous reconnects due to "HttpError - Trying again in 2 second/s -> Lost connection [1].". It seems problem in particular link because if i skip error page, last job work normally.

example of problem tag - the_witcher_(series)

If it problem on sankaku side is it possible make auto-skip such links and continue work on other?

[05-06-2019_errorlog.txt](https://github.com/CryShana/Sankaku-Channel-Downloader/files/3255363/05-06-2019_errorlog.txt)

**Comment by Hellbeast** [comment]
![изображение](https://user-images.githubusercontent.com/23698179/58982108-24729a00-87ed-11e9-8ddf-ba9555a0c81a.png)

**Comment by CryShana** [comment]
Nice suggestion. Will probably add a "Skip after X tries" textbox.

**Comment by CryShana** [comment]
I didn't have time to test it out personally, but you can try out this release:
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.2.5

I added a "Max retries" setting that you can try playing with. I tested it really quickly, so it might have some bugs. Post feedback.

**Comment by Hellbeast** [comment]
'Max retries' seems working i successfully download tags with broken posts, but if list to previously downloaded links click rmb and choose 'open file' it some times cause crash
![изображение](https://user-images.githubusercontent.com/23698179/59331979-a7748280-8d0e-11e9-93b8-489dcdc4d883.png)

**Comment by CryShana** [comment]
Thanks for the feedback. I can't seem to reproduce this issue though.

I don't have much time to test the program out, so if you find out the exact steps to reproduce this error, tell me and I will try to fix it then.
