### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by UWNG99** [CryShana/Sankaku-Channel-Downloader#5]
Hi, I think it is great that you are developing this program, however, I have a problemwhen starting it, it asks me for login credentials and even if I provide them correctly, they are rejected and this doesn't allow me to start the program, I hope this helps to improve your program.

**Comment by CryADsisAM** [comment]
Sorry to disappoint you, but I am no longer actively developing this, as this was just made as a side project. I will fix any small bugs that might occur when I have the time - but the login process seems to be still functional for me. 

This error seems to be happening on your side - you are free to do your own investigation on the error and report back here - but I am not going to be looking deeper into solving this. (If I had to guess - the error is probably somewhere in the HTTP requests while logging in - the website had some changes lately - but the login should not have been changed...)

**Comment by UWNG99** [comment]
No problem pal, I will investigate on my side and if something arises I will post it here, thanks for your attention.
