### ISSUE TITLE
is there any kind of file that it wont download?

### ISSUE THREAD

**Issue by Kenjiro31** [CryShana/Sankaku-Channel-Downloader#6]
First of all i love this program.  Glad someone even thought on making one.
So when i search for a tag i can see how many images/files are in there.
say i wanna get a full category with lets say 25 images.
it usually ends up getting always -1 or -2 files. 
havent tried with big Tags but i believe it might happen more if the tag is bigger,
wanted to ask if theres a particular file that wont get downloaded or if theres a bug.
thank you
-Kenjiro

**Comment by CryShana** [comment]
Thank you for your kind words. This is an old project and is no longer being developed. From what I remember, the program SHOULD download everything - but as you know - the site changed while this program did not.

Lately I've been having more and more requests for this program - I might decide to make a new downloader soon (maybe this month). In the meantime - could you tell me which tags you used?

**Comment by Kenjiro31** [comment]
ginhaha, and  aposine ,  were the only one i remember rn .
Thanks for your response by the way
