### ISSUE TITLE
I love it

### ISSUE THREAD

**Issue by maxman2103** [CryShana/Sankaku-Channel-Downloader#7]
i want to say i love a software that can acually download from sankaku. i know its no longer in dev..but i was wondering when i download batch images is there any way to know how much image left to download?? or a way to pause it so i can downloade the rest later??

**Comment by CryShana** [comment]
Thanks. Unfortunately there is no way to view that or pause downloads as this program wasn't even made to be that advanced... Sankaku is currently doing some changes to their API - I will most likely make a completely new downloader in the following months using the new API (or temporarily using the current slower method of downloading images). So wait until then...
