### ISSUE TITLE
Not downloading (or even counting) some images. 

### ISSUE THREAD

**Issue by Nyanyanyanyan** [CryShana/Sankaku-Channel-Downloader#8]
I tried downloading all images from a certain tag (hamada_yoshikazu) and the downloader skipped every second image per page. It found 19 images per page (regardless of image/page setting).
Second I tried a few more tags and it skipped even more images (found 43 of 54 images).

Couldn't fix it by playing around with the settings. 

Hope you'll fix this even though it says development closed.
I was really happy when I found this since it's a huge pain to download all the images manually and sadly sankaku is pretty much the only (mostly) comprehensive source for anime style drawings.

**Comment by CryShana** [comment]
I honestly really want to update this app too, but I just can't find the time to do it. The code is terrible and I will probably build the app from scratch when I get the time.

I can't really give you an ETA but I'm hoping to update the app in the following few months. (Maybe even this one if I get lucky with time)

**Comment by CryShana** [comment]
Nevermind. It seems I will be done with this much quicker than I thought.

**Comment by CryShana** [comment]
Thanks to the new API being simpler now, I have managed to update the app entirely. Check the releases. 
[https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1](url)

**Comment by Nyanyanyanyan** [comment]
Thank you so much for updating this app. Everything works beautifully now.
You're a hero.
