### ISSUE TITLE
Downloading After page 50!

### ISSUE THREAD

**Issue by KaleyMoro** [CryShana/Sankaku-Channel-Downloader#9]
I know you are not counting this project ,but can you please solve the issue, it says error massage. this page API keeps updating and the app is not up to date, so could you please solve this issue.
![untitled](https://user-images.githubusercontent.com/39103357/39958053-1ca14838-561d-11e8-930c-7b43c8d7357d.png)

**Comment by CryShana** [comment]
I will most likely be updating this app in the following months if I get the time. Wait until then.

**Comment by CryShana** [comment]
Thanks to the new API being simpler now, I have managed to update the app entirely. Check the releases. 
[https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1](url)

**Comment by KaleyMoro** [comment]
you talking about this: https://beta.sankakucomplex.com/
new api

**Comment by CryShana** [comment]
Yeah. They always had an API that the mobile app used but I never had the time to debug that one - but now that they started working on the beta site - the beta API became easier to debug - so I just used it.
